In [13]:
import pandas as pd
import gc
import numpy as np
import tqdm

from matplotlib import pyplot as plt
from sklearn.metrics import roc_auc_score
%matplotlib inline

Подгрузим train данные.

In [14]:
train = pd.read_csv('../data/data/train.csv')

In [15]:
train.head(100)

,C_Year,EtalonPosName,R_Year,age_qty,boss_pos_name,boss_subord_1y_max_qty,boss_subord_1y_min_qty,boss_subord_in_1m_qty,boss_subord_in_1y_qty,boss_subord_out_1m_qty,...,up_day_nv_sum_3m,up_day_nv_sum_6m,vl_nv_KBP_sum_3m,vl_nv_KBP_sum_6m,vl_nv_MP_sum_3m,vl_nv_MP_sum_6m,vl_nv_sum_3m,vl_nv_sum_6m,vsp_cd,work_rate_pct
0,NaN,0.0,NaN,27.0,0.0,28.0,0.0,1.0,29.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0,1.0
1,C,0.0,C,24.0,0.0,31.0,26.0,2.0,23.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1.0
2,D,0.0,C,52.0,0.0,31.0,26.0,1.0,19.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1.0
3,NaN,0.0,NaN,28.0,0.0,15.0,14.0,2.0,3.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,1.0
4,NaN,0.0,NaN,25.0,0.0,13.0,12.0,0.0,5.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,4,1.0
5,NaN,0.0,NaN,30.0,0.0,11.0,9.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,5,1.0
6,C,0.0,D,27.0,0.0,14.0,13.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,1.0
7,C,0.0,D,24.0,0.0,16.0,13.0,1.0,10.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,1.0
8,B,0.0,B,30.0,0.0,16.0,10.0,1.0,4.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,8,1.0
9,B,0.0,C,26.0,0.0,31.0,20.0,0.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,1.0
10,NaN,0.0,NaN,29.0,0.0,13.0,11.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,10,1.0
11,C,0.0,C,28.0,0.0,35.0,27.0,0.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11,1.0
12,C,0.0,C,28.0,0.0,31.0,27.0,1.0,12.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12,1.0
13,NaN,0.0,NaN,24.0,0.0,15.0,15.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,13,1.0
14,C,0.0,C,40.0,0.0,41.0,37.0,0.0,15.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14,1.0
15,D,0.0,C,38.0,0.0,15.0,15.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15,1.0
16,B,0.0,B,29.0,0.0,17.0,14.0,0.0,5.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16,1.0
17,C,0.0,E,22.0,0.0,45.0,0.0,2.0,68.0,3.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,17,1.0
18,C,0.0,C,28.0,0.0,27.0,22.0,2.0,9.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,1.0
19,C,0.0,C,25.0,0.0,20.0,17.0,1.0,16.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19,1.0
20,NaN,0.0,NaN,29.0,0.0,12.0,12.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,20,1.0
21,C,0.0,D,21.0,0.0,32.0,26.0,0.0,7.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,1.0
22,C,0.0,C,21.0,0.0,28.0,25.0,1.0,14.0,1.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,22,1.0
23,D,0.0,C,22.0,0.0,18.0,11.0,1.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23,1.0
24,C,0.0,D,26.0,0.0,20.0,10.0,2.0,6.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24,1.0
25,B,0.0,C,24.0,0.0,24.0,23.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25,1.0
26,C,0.0,C,30.0,0.0,52.0,41.0,1.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26,1.0
27,NaN,0.0,NaN,28.0,0.0,33.0,27.0,1.0,14.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,27,1.0
28,C,0.0,C,29.0,0.0,38.0,30.0,0.0,17.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28,1.0
29,B,0.0,B,30.0,2.0,27.0,24.0,0.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,C,0.0,A,25.0,0.0,15.0,11.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68,1.0
71,C,0.0,C,23.0,0.0,28.0,23.0,0.0,14.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69,1.0
72,NaN,0.0,NaN,29.0,0.0,42.0,32.0,0.0,34.0,1.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,70,1.0
73,B,0.0,C,39.0,0.0,14.0,10.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71,1.0
74,NaN,0.0,NaN,41.0,0.0,35.0,17.0,8.0,29.0,1.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,72,1.0
75,C,0.0,C,51.0,0.0,9.0,7.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73,1.0
76,C,0.0,C,24.0,0.0,19.0,15.0,0.0,12.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74,1.0
77,B,0.0,B,28.0,0.0,40.0,40.0,6.0,6.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75,1.0
78,C,0.0,C,30.0,0.0,13.0,11.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76,1.0
79,C,0.0,C,32.0,0.0,22.0,18.0,1.0,17.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77,0.0
80,C,0.0,C,41.0,0.0,4.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,78,1.0
81,C,0.0,B,35.0,0.0,20.0,17.0,3.0,13.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79,1.0
82,C,0.0,C,32.0,0.0,26.0,18.0,1.0,13.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41,1.0
83,C,0.0,D,23.0,0.0,21.0,19.0,1.0,8.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,1.0
84,C,0.0,C,32.0,0.0,28.0,0.0,1.0,29.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1.0
85,NaN,0.0,NaN,25.0,0.0,17.0,15.0,1.0,5.0,1.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,81,1.0
86,NaN,0.0,NaN,29.0,0.0,18.0,15.0,3.0,16.0,3.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,66,1.0
87,C,0.0,B,21.0,0.0,20.0,16.0,0.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82,1.0
88,NaN,0.0,NaN,26.0,0.0,11.0,11.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,83,1.0
89,C,0.0,B,26.0,0.0,32.0,28.0,1.0,10.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84,0.0
90,NaN,0.0,NaN,19.0,0.0,12.0,10.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,85,1.0
91,C,0.0,C,32.0,0.0,34.0,34.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,86,1.0
92,C,0.0,C,32.0,0.0,17.0,13.0,0.0,7.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87,1.0
93,C,0.0,B,29.0,0.0,12.0,9.0,0.0,4.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30,1.0
94,C,0.0,C,52.0,0.0,10.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88,1.0
95,B,0.0,A,29.0,0.0,15.0,13.0,1.0,8.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,89,1.0
96,C,0.0,C,28.0,0.0,24.0,18.0,0.0,14.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90,1.0
97,B,0.0,C,28.0,0.0,25.0,19.0,0.0,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,91,1.0
98,B,0.0,C,31.0,0.0,29.0,21.0,3.0,14.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92,1.0
99,C,0.0,D,31.0,0.0,13.0,5.0,0.0,6.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93,1.0

Подгрузим test данные.

In [16]:
test = pd.read_csv('../data/data/test.csv')

In [17]:
test.head()

,C_Year,EtalonPosName,R_Year,age_qty,boss_pos_name,boss_subord_1y_max_qty,boss_subord_1y_min_qty,boss_subord_in_1m_qty,boss_subord_in_1y_qty,boss_subord_out_1m_qty,...,up_day_nv_sum_3m,up_day_nv_sum_6m,vl_nv_KBP_sum_3m,vl_nv_KBP_sum_6m,vl_nv_MP_sum_3m,vl_nv_MP_sum_6m,vl_nv_sum_3m,vl_nv_sum_6m,vsp_cd,work_rate_pct
0,C,0.0,C,45.0,0.0,21.0,17.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,196,1.0
1,B,0.0,B,26.0,0.0,27.0,24.0,1.0,9.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,681,1.0
2,NaN,0.0,NaN,26.0,0.0,20.0,18.0,0.0,11.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1175,1.0
3,NaN,0.0,NaN,33.0,0.0,59.0,52.0,3.0,33.0,2.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,485,1.0
4,C,0.0,C,25.0,1.0,19.0,0.0,1.0,25.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,366,1.0

В файле use_columns находятся описания фичей. ВНИМАНИЕ: не у всех фичей есть описания, обычно это числовые агрегаты каких то функций за определенный промежуток времени.

In [18]:
feature_description = pd.read_excel('../data/data/columns_description.xlsx')

In [19]:
feature_description.head(100)

,name,description
0,C_Year,NaN
1,EtalonPosName,NaN
2,R_Year,NaN
3,age_qty,Возраст сотрудника (должно стать вычисляемым п...
4,boss_pos_name,Название должности непосредственного руководит...
5,boss_subord_1y_max_qty,NaN
6,boss_subord_1y_min_qty,NaN
7,boss_subord_in_1m_qty,NaN
8,boss_subord_in_1y_qty,NaN
9,boss_subord_out_1m_qty,NaN
10,boss_subord_out_1y_qty,NaN
11,boss_subord_qty,NaN
12,boss_tabnum,Табельный номер непосредственного руководителя...
13,crd_cc_act_qty,Кол-во активных действующих кредитных карт (де...
14,crd_cc_act_spend_qty,Кол-во активных по расходным операциям кредитн...
15,crd_cc_ever_nflag,Флаг наличия кредитной карты когда-либо
16,crd_cc_mnth_snc_issue_frac,NaN
17,crd_cc_mnth_snc_issue_qty,NaN
18,crd_cc_overdue_nflag,Флаг наличия просрочки по КК
19,crd_cc_own_bal_rub_amt,Сумма собственных средств на КК на отчетную да...
20,crd_cc_pos_auto_qty,"Количество операций покупки в категории ""Авто/..."
21,crd_cc_pos_auto_rub_amt,"Сумма операций покупки в категории ""Авто/мото""..."
22,crd_cc_pos_beuaty_qty,"Количество операций покупки в категории ""Красо..."
23,crd_cc_pos_beuaty_rub_amt,"Сумма операций покупки в категории ""Красота и ..."
24,crd_cc_pos_clothes_qty,"Количество операций покупки в категории ""Одежд..."
25,crd_cc_pos_clothes_rub_amt,"Сумма операций покупки в категории ""Одежда, об..."
26,crd_cc_pos_dept_stores_qty,"Количество операций покупки в категории ""Униве..."
27,crd_cc_pos_dept_stores_rub_amt,"Сумма операций покупки в категории ""Универсаль..."
28,crd_cc_pos_eat_out_qty,"Количество операций покупки в категории ""Кафе/..."
29,crd_cc_pos_eat_out_rub_amt,"Сумма операций покупки в категории ""Кафе/бары/..."
...,...,...
70,crd_dc_pos_dept_stores_qty,"Количество операций покупки в категории ""Униве..."
71,crd_dc_pos_dept_stores_rub_amt,"Сумма операций покупки в категории ""Универсаль..."
72,crd_dc_pos_eat_out_qty,"Количество операций покупки в категории ""Кафе/..."
73,crd_dc_pos_eat_out_rub_amt,"Сумма операций покупки в категории ""Кафе/бары/..."
74,crd_dc_pos_groceries_qty,"Количество операций покупки в категории ""Проду..."
75,crd_dc_pos_groceries_rub_amt,"Сумма операций покупки в категории ""Продукты"" ..."
76,crd_dc_pos_healthcare_qty,"Количество операций покупки в категории ""Медиц..."
77,crd_dc_pos_healthcare_rub_amt,"Сумма операций покупки в категории ""Медицина"" ..."
78,crd_dc_pos_home_repair_qty,"Количество операций покупки в категории ""Товар..."
79,crd_dc_pos_home_repair_rub_amt,"Сумма операций покупки в категории ""Товары для..."
80,crd_dc_pos_leisure_qty,"Количество операций покупки в категории ""Отдых..."
81,crd_dc_pos_leisure_rub_amt,"Сумма операций покупки в категории ""Отдых/разв..."
82,crd_dc_pos_money_trf_qty,"Количество операций покупки в категории ""Безна..."
83,crd_dc_pos_money_trf_rub_amt,"Сумма операций покупки в категории ""Безналичны..."
84,crd_dc_pos_othr_qty,"Количество операций покупки в категории ""Проче..."
85,crd_dc_pos_othr_rub_amt,"Сумма операций покупки в категории ""Прочее"" в ..."
86,crd_dc_pos_pc_it_qty,"Количество операций покупки в категории ""Компь..."
87,crd_dc_pos_pc_it_rub_amt,"Сумма операций покупки в категории ""Компьютеры..."
88,crd_dc_pos_special_qty,"Количество операций покупки в категории ""Специ..."
89,crd_dc_pos_special_rub_amt,"Сумма операций покупки в категории ""Специализи..."
90,crd_dc_pos_telecom_qty,"Количество операций покупки в категории ""Телек..."
91,crd_dc_pos_telecom_rub_amt,"Сумма операций покупки в категории ""Телекоммун..."
92,crd_dc_pos_tourism_qty,"Количество операций покупки в категории ""Туриз..."
93,crd_dc_pos_tourism_rub_amt,"Сумма операций покупки в категории ""Туризм/тра..."
94,crd_dc_pos_utilities_qty,"Количество операций покупки в категории ""Комму..."
95,crd_dc_pos_utilities_rub_amt,"Сумма операций покупки в категории ""Коммунальн..."
96,crd_dc_social_nflag,Флаг наличия у клиента открытой действующей со...
97,crd_ever_nflag,NaN
98,crd_inf_cash_adv_qty,Общее количество операций взноса наличных по в...
99,crd_inf_cash_adv_rub_amt,Общая сумма операций взноса наличных по всем к...

Дополнительные данные - это информация по логинам клиентов. Их можно использовать на ваше усмотрение. Пересечение с основными данными (train/test) идет через поле **tabnum**.

In [20]:
logins = pd.read_csv('../data/data/valid_logins.csv')

In [84]:
import datetime
logins_mod = logins
logins_mod['work_begins_mod'] = pd.to_datetime(logins_mod['business_dt'] + ' ' + logins_mod['work_begins'] , format="%Y-%m-%d %H:%M:%S")
logins_mod['work_ends_mod'] = pd.to_datetime(logins_mod['business_dt'] + ' ' + logins_mod['work_ends'] , format="%Y-%m-%d %H:%M:%S")
logins_mod['work_duration'] = logins_mod['work_ends_mod'] - logins_mod['work_begins_mod']
logins_mod['work_duration_sec'] = logins_mod['work_duration'].dt.total_seconds()
logins_mod['business_dt_month'] = logins_mod['business_dt'].str[:7].str.replace('-','')
logins_mod.head()

,business_dt,tabnum,work_time_day,work_begins,work_ends,,work_begins_mod,work_ends_mod,work_duration,work_duration_sec,business_dt_month
0,2017-06-13,0,423,18:40:44,19:02:28,2017-06-13 18:40:44,2017-06-13 18:40:44,2017-06-13 19:02:28,00:21:44,1304.0,201706
1,2018-10-23,0,30652,09:00:27,18:59:51,2018-10-23 09:00:27,2018-10-23 09:00:27,2018-10-23 18:59:51,09:59:24,35964.0,201810
2,2017-06-22,0,1724,18:57:29,19:36:28,2017-06-22 18:57:29,2017-06-22 18:57:29,2017-06-22 19:36:28,00:38:59,2339.0,201706
3,2017-04-29,0,1934,12:25:34,17:20:21,2017-04-29 12:25:34,2017-04-29 12:25:34,2017-04-29 17:20:21,04:54:47,17687.0,201704
4,2018-06-10,0,4920,11:42:39,17:24:23,2018-06-10 11:42:39,2018-06-10 11:42:39,2018-06-10 17:24:23,05:41:44,20504.0,201806

In [ ]:
logins_agg = pd.DataFrame()
i = 0
for tabnum in logins_mod['tabnum'].unique():
    logins_cur = logins_mod[logins_mod.tabnum == tabnum]
    logins_mod[logins_mod.tabnum == tabnum].['tabnum', ]
    
    i = i + 1
    if i>99:
        break

В бэйзлайне никакой обработки фичей не производится. Для датасетов train/test удаляются dt фичи(временные). Каждую колонку пытаемся привести к числовому типу, если не получается - заполняем NaN. Соответственно, модель для примера  будет обучаться без любых временных и категориальных фичей.

In [10]:
train.drop([i for i in train.columns if 'dt' in i],axis=1,inplace=True)
for i in tqdm.tqdm_notebook(train.columns):
    train[i] = pd.to_numeric(train[i],errors='coerce')
print(train.shape)

HBox(children=(IntProgress(value=0, max=392), HTML(value='')))

(449576, 392)

In [11]:
test.drop([i for i in test.columns if 'dt' in i],axis=1,inplace=True)
for i in tqdm.tqdm_notebook(test.columns):
    test[i] = pd.to_numeric(test[i],errors='coerce')
print(test.shape)

HBox(children=(IntProgress(value=0, max=391), HTML(value='')))

(24000, 391)

In [12]:
from xgboost import XGBClassifier

In [13]:
xgb = XGBClassifier(n_jobs=4,random_state=42)
X_train, y_train = train.drop('target_churn_lag1m',axis=1), train['target_churn_lag1m']

In [14]:
%%time
xgb.fit(X_train,y_train)

Wall time: 7min 1s

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=4, nthread=None,
       objective='binary:logistic', random_state=42, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [15]:
prediction = xgb.predict_proba(test)[:,1]

Это решение даёт на паблике около 0.75564 ROC AUC

Пример файла решения, которое ожидает на вход платформа:

In [16]:
sample_submission = pd.DataFrame({'tabnum': test['tabnum'], 'prob': prediction})
sample_submission.to_csv('sample_submission.csv')